### ISSUE TITLE
4.23 Support

### ISSUE THREAD

**Issue by macabr0ni** [feixuwu/EasyFirebase#10]
Hi, very nice plugin!

I'm currently stuck using UE4.23 because in addition to iOS and Android we work with HTML5 and Epic dropped support for HTML5 in 4.24.
Can you add support for 4.23? I would like to use your plugin. All the alternatives are expensive and it seems like support there isn't the best..

Thanks :)

**Comment by feixuwu** [comment]
sorry,I have no time to support 4.23 HTML5,
it's not an easy work, need a lof of time.

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by macabr0ni** [comment]
Ok, thanks anyway!
