### ISSUE TITLE
How do i get analytics data in firebase console?

### ISSUE THREAD

**Issue by manuganu9** [feixuwu/EasyFirebase#3]
Hi, 
Thank you for the wonderful plugin.  I analyzed your sample project and Integrated my **google-services.json** file, and linked the app id, cloud messaging id, but i'm unable to see the analytics in Firebase console. 

How do i get analytics ? How do integrate dynamic link and app indexing feature ?

**Comment by feixuwu** [comment]
this plugin is not include firebase/google analytics

**Comment by feixuwu** [comment]
the plugin add analytics support now
