### ISSUE TITLE
Listener Issue

### ISSUE THREAD

**Issue by MrMcCarty** [feixuwu/EasyFirebase#8]
First of all I want to thank you for this great plugin.
However, I do not know whether it is due to my settings or whether it is a problem with the plugin. The listener (neither the value nor the child) stops listening after a time. Can you confirm it?

**Comment by feixuwu** [comment]
Add Child?
I think you may not add child, just update child value, but u listen add child event?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by feixuwu** [comment]
I will check it next few days

**Comment by feixuwu** [comment]
I have fixed it, please:
1. pull the latest content and replace in your projejct.
2.add a variable in UMG or game mode, else the databaseref will be free by GC, please check the demo project.

**Comment by MrMcCarty** [comment]
Thank you. I tested it and everything works again.
